services:
  sas_core:
    build: .
    volumes:
      - ../../sas_core:/root/sas_core_devel/src/sas_core
    environment:
      PYTHONUNBUFFERED: 1
    command: /bin/bash -c "
      cd /root/sas_core_devel/src/
      && ls .
      && colcon build
      && source install/setup.bash
      && ros2 run sas_core sas_clock_example
      && ros2 run sas_core sas_clock_example_py.py
      && ros2 run sas_core sas_robot_driver_example
      && ros2 run sas_core sas_robot_driver_subclass_example_py.py
      && ros2 run sas_core sas_clock_sched_fifo_example
      && ros2 run sas_core sas_clock_sched_fifo_example_py.py
      "